python Generate.py `
    --save_path F:\KMC_data\data_2020_10_18_random_mix_amp_v1\4 `
    --split 1 `
    --base_periods 2.5 `
    --window_points 256 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.04 `
    --energy_base 0.0 

python Generate.py `
    --save_path F:\KMC_data\data_2020_10_18_random_mix_amp_v1\3 `
    --split 1 `
    --base_periods 2.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.03 `
    --energy_base 0.0 

python Generate.py `
    --save_path F:\KMC_data\data_2020_10_18_random_mix_amp_v1\2 `
    --split 1 `
    --base_periods 2.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.025 `
    --energy_base 0.0 

python Generate.py `
    --save_path F:\KMC_data\data_2020_10_18_random_mix_amp_v1\1 `
    --split 1 `
    --base_periods 2.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.01 `
    --energy_base 0.0 
