python Generate.py `
    --save_path F:\KMC_data\data_2020_09_23_random_mix_amp_max `
    --split 1 `
    --base_periods 1.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.1 `
    --energy_base 0.0 

python Generate.py `
    --save_path F:\KMC_data\data_2020_09_23_random_mix_amp_mid `
    --split 1 `
    --base_periods 1.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.01 `
    --energy_base 0.0 

python Generate.py `
    --save_path F:\KMC_data\data_2020_09_23_random_mix_amp_low `
    --split 1 `
    --base_periods 1.5 `
    --window_points 200 `
    --low_freq 7 `
    --high_freq 10 `
    --cell_type random `
    --model_size 11 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.001 `
    --energy_base 0.0 
