python Generate.py `
    --save_path F:\KMC_data\data_2020_09_23_random `
    --split 1 `
    --base_periods 0.5 `
    --window_points 200 `
    --low_freq 8 `
    --high_freq 10 `
    --cell_type random `
    --model_size 7 7 7 `
    --thermalization_time 200 `
    --window 100 `
    --window_epsilon 0.01 `
    --contact_switch_left False `
    --contact_switch_right False `
    --contact_left 1 `
    --contact_right 1 `
    --amplitude 0.1 `
    --energy_base 0.0 `
