# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\kmc_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KMC_GUI(object):
    def setupUi(self, KMC_GUI):
        KMC_GUI.setObjectName("KMC_GUI")
        KMC_GUI.resize(771, 623)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KMC_GUI.sizePolicy().hasHeightForWidth())
        KMC_GUI.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(KMC_GUI)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidge = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidge.setGeometry(QtCore.QRect(0, 0, 711, 541))
        self.tabWidge.setObjectName("tabWidge")
        self.tab_generate = QtWidgets.QWidget()
        self.tab_generate.setObjectName("tab_generate")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_generate)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 475))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 14, 0, 1, 1)
        self.doubleSpinBox_delta_energi_base = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_delta_energi_base.setDecimals(5)
        self.doubleSpinBox_delta_energi_base.setMinimum(-99999.99)
        self.doubleSpinBox_delta_energi_base.setMaximum(99999.99)
        self.doubleSpinBox_delta_energi_base.setObjectName("doubleSpinBox_delta_energi_base")
        self.gridLayout.addWidget(self.doubleSpinBox_delta_energi_base, 13, 1, 1, 1)
        self.spinBox_left_contact = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_left_contact.setMinimum(1)
        self.spinBox_left_contact.setMaximum(99999)
        self.spinBox_left_contact.setObjectName("spinBox_left_contact")
        self.gridLayout.addWidget(self.spinBox_left_contact, 7, 1, 1, 1)
        self.checkBox_right_contact = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_right_contact.setObjectName("checkBox_right_contact")
        self.gridLayout.addWidget(self.checkBox_right_contact, 9, 2, 1, 1)
        self.pushButton_path_to_data = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_path_to_data.setObjectName("pushButton_path_to_data")
        self.gridLayout.addWidget(self.pushButton_path_to_data, 14, 1, 1, 1)
        self.checkBox_left_contact = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_left_contact.setObjectName("checkBox_left_contact")
        self.gridLayout.addWidget(self.checkBox_left_contact, 7, 2, 1, 1)
        self.spinBox_right_contact = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_right_contact.setMinimum(1)
        self.spinBox_right_contact.setMaximum(99999)
        self.spinBox_right_contact.setObjectName("spinBox_right_contact")
        self.gridLayout.addWidget(self.spinBox_right_contact, 9, 1, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.gridLayout.addWidget(self.comboBox_type, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_y_size = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_y_size.setMinimum(3)
        self.spinBox_y_size.setMaximum(999)
        self.spinBox_y_size.setProperty("value", 7)
        self.spinBox_y_size.setObjectName("spinBox_y_size")
        self.gridLayout.addWidget(self.spinBox_y_size, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.spinBox_z_size = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_z_size.setMinimum(3)
        self.spinBox_z_size.setMaximum(999)
        self.spinBox_z_size.setProperty("value", 7)
        self.spinBox_z_size.setObjectName("spinBox_z_size")
        self.gridLayout.addWidget(self.spinBox_z_size, 4, 1, 1, 1)
        self.spinBox_x_size = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_x_size.setMinimum(3)
        self.spinBox_x_size.setMaximum(999)
        self.spinBox_x_size.setProperty("value", 15)
        self.spinBox_x_size.setObjectName("spinBox_x_size")
        self.gridLayout.addWidget(self.spinBox_x_size, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.spinBox_time_end = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_time_end.setMaximum(9999999)
        self.spinBox_time_end.setProperty("value", 1000)
        self.spinBox_time_end.setObjectName("spinBox_time_end")
        self.gridLayout.addWidget(self.spinBox_time_end, 6, 1, 1, 1)
        self.pushButton_generate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.gridLayout.addWidget(self.pushButton_generate, 17, 0, 1, 3)
        self.label_path_to_data = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_path_to_data.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_path_to_data.setText("")
        self.label_path_to_data.setObjectName("label_path_to_data")
        self.gridLayout.addWidget(self.label_path_to_data, 0, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.doubleSpinBox_period = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_period.setDecimals(5)
        self.doubleSpinBox_period.setMaximum(9999.99)
        self.doubleSpinBox_period.setObjectName("doubleSpinBox_period")
        self.gridLayout.addWidget(self.doubleSpinBox_period, 12, 1, 1, 1)
        self.doubleSpinBox_A = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_A.setDecimals(5)
        self.doubleSpinBox_A.setMaximum(9999.99)
        self.doubleSpinBox_A.setObjectName("doubleSpinBox_A")
        self.gridLayout.addWidget(self.doubleSpinBox_A, 11, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 12, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 10, 0, 1, 3)
        self.tabWidge.addTab(self.tab_generate, "")
        self.tab_launch = QtWidgets.QWidget()
        self.tab_launch.setObjectName("tab_launch")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_launch)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 641, 451))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_models = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_models.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label_models.setText("")
        self.label_models.setObjectName("label_models")
        self.gridLayout_2.addWidget(self.label_models, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.pushButton_launch = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_launch.setObjectName("pushButton_launch")
        self.gridLayout_2.addWidget(self.pushButton_launch, 5, 0, 1, 2)
        self.spinBox_threads = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_threads.setProperty("value", 1)
        self.spinBox_threads.setObjectName("spinBox_threads")
        self.gridLayout_2.addWidget(self.spinBox_threads, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add_model = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_add_model.setObjectName("pushButton_add_model")
        self.verticalLayout.addWidget(self.pushButton_add_model)
        self.pushButton_clear_all = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_clear_all.setObjectName("pushButton_clear_all")
        self.verticalLayout.addWidget(self.pushButton_clear_all)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.tabWidge.addTab(self.tab_launch, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_analysis)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(-1, -1, 711, 511))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_add_root = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_add_root.setObjectName("pushButton_add_root")
        self.gridLayout_6.addWidget(self.pushButton_add_root, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 4, 0, 1, 1)
        self.spinBox_layer = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.spinBox_layer.setObjectName("spinBox_layer")
        self.gridLayout_6.addWidget(self.spinBox_layer, 4, 1, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout_6.addWidget(self.pushButton_plot, 4, 2, 1, 1)
        self.label_roots = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_roots.setText("")
        self.label_roots.setObjectName("label_roots")
        self.gridLayout_6.addWidget(self.label_roots, 0, 0, 1, 3)
        self.pushButton_heatmap = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_heatmap.setObjectName("pushButton_heatmap")
        self.gridLayout_6.addWidget(self.pushButton_heatmap, 10, 0, 1, 3)
        self.tabWidge.addTab(self.tab_analysis, "")
        KMC_GUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(KMC_GUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menuBar.setObjectName("menuBar")
        KMC_GUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(KMC_GUI)
        self.mainToolBar.setObjectName("mainToolBar")
        KMC_GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(KMC_GUI)
        self.statusBar.setObjectName("statusBar")
        KMC_GUI.setStatusBar(self.statusBar)

        self.retranslateUi(KMC_GUI)
        self.tabWidge.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KMC_GUI)

    def retranslateUi(self, KMC_GUI):
        _translate = QtCore.QCoreApplication.translate
        KMC_GUI.setWindowTitle(_translate("KMC_GUI", "KMC_GUI"))
        self.label_6.setText(_translate("KMC_GUI", "Path to Data"))
        self.checkBox_right_contact.setText(_translate("KMC_GUI", "CheckBox"))
        self.pushButton_path_to_data.setText(_translate("KMC_GUI", "Browse"))
        self.checkBox_left_contact.setText(_translate("KMC_GUI", "CheckBox"))
        self.comboBox_type.setItemText(0, _translate("KMC_GUI", "Random"))
        self.comboBox_type.setItemText(1, _translate("KMC_GUI", "Sphere"))
        self.comboBox_type.setItemText(2, _translate("KMC_GUI", "Plane"))
        self.label_9.setText(_translate("KMC_GUI", "Type"))
        self.label.setText(_translate("KMC_GUI", "Z"))
        self.label_3.setText(_translate("KMC_GUI", "X"))
        self.label_4.setText(_translate("KMC_GUI", "Time End"))
        self.label_2.setText(_translate("KMC_GUI", "Y"))
        self.pushButton_generate.setText(_translate("KMC_GUI", "Generate"))
        self.label_10.setText(_translate("KMC_GUI", "Root Directory"))
        self.label_8.setText(_translate("KMC_GUI", "Right Contact"))
        self.label_7.setText(_translate("KMC_GUI", "Left Contact"))
        self.label_5.setText(_translate("KMC_GUI", "Delta Energy Base"))
        self.label_14.setText(_translate("KMC_GUI", "Period"))
        self.label_11.setText(_translate("KMC_GUI", "A"))
        self.label_16.setText(_translate("KMC_GUI", "delta energy = A*sin(time*perion)+delta energy base"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_generate), _translate("KMC_GUI", "Generate"))
        self.label_12.setText(_translate("KMC_GUI", "Select models"))
        self.pushButton_launch.setText(_translate("KMC_GUI", "Launch"))
        self.label_13.setText(_translate("KMC_GUI", "Threads"))
        self.pushButton_add_model.setText(_translate("KMC_GUI", "Add"))
        self.pushButton_clear_all.setText(_translate("KMC_GUI", "Clear All"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_launch), _translate("KMC_GUI", "Launch"))
        self.pushButton_add_root.setText(_translate("KMC_GUI", "Add"))
        self.label_27.setText(_translate("KMC_GUI", "Plot heatmap for layer in time"))
        self.pushButton_plot.setText(_translate("KMC_GUI", "Plot"))
        self.pushButton_heatmap.setText(_translate("KMC_GUI", "Heatmap"))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_analysis), _translate("KMC_GUI", "Analysis"))


